return {
	-- ==========================================
	-- CLOTH ARMOR (Mages, Clerics, Warlocks, etc.)
	-- ==========================================
	Headwear_Novice_Cloth = {
		Name = "Novice Cloth Hood",
		Slot = "Headwear",
		ArmorType = "Cloth",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { MagicResistance = 2, Spirit = 1, CastSpeed = 0.01 },
	},
	Shoulder_Novice_Cloth = {
		Name = "Novice Cloth Pauldrons",
		Slot = "Shoulder",
		ArmorType = "Cloth",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { MagicResistance = 2, Spirit = 1, Tenacity = 0.01 },
	},
	UpperBody_Novice_Cloth = {
		Name = "Novice Cloth Tunic",
		Slot = "UpperBody",
		ArmorType = "Cloth",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { PhysicalDefense = 1, MagicResistance = 3, Spirit = 1, Intelligence = 1, MPRegen = 0.5 },
	},
	Waist_Novice_Cloth = {
		Name = "Novice Cloth Sash",
		Slot = "Waist",
		ArmorType = "Cloth",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { MagicResistance = 1, Spirit = 1, MPRegen = 0.2 },
	},
	LowerBody_Novice_Cloth = {
		Name = "Novice Cloth Pants",
		Slot = "LowerBody",
		ArmorType = "Cloth",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { MagicResistance = 2, Spirit = 1, CastSpeed = 0.01 },
	},
	Cloak_Novice_Cloth = {
		Name = "Traveler's Cloak",
		Slot = "Cloak",
		ArmorType = "Cloth",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { Spirit = 2, MovementSpeed = 0.02 },
	},

	-- ==========================================
	-- LEATHER ARMOR (Assassins, Thieves, Sharpshooters, Brawlers)
	-- ==========================================
	Headwear_Novice_Leather = {
		Name = "Basic Leather Cap",
		Slot = "Headwear",
		ArmorType = "Leather",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { PhysicalDefense = 2, MagicResistance = 1, Strength = 1, AttackSpeed = 0.01 },
	},
	Shoulder_Novice_Leather = {
		Name = "Novice Leather Pauldrons",
		Slot = "Shoulder",
		ArmorType = "Leather",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { PhysicalDefense = 2, MagicResistance = 1, Strength = 1, Evasion = 0.01 },
	},
	UpperBody_Novice_Leather = {
		Name = "Novice Leather Vest",
		Slot = "UpperBody",
		ArmorType = "Leather",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { PhysicalDefense = 3, MagicResistance = 1, Strength = 1, Vitality = 1 },
	},
	Waist_Novice_Leather = {
		Name = "Novice Leather Belt",
		Slot = "Waist",
		ArmorType = "Leather",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { PhysicalDefense = 1, Strength = 1 },
	},
	LowerBody_Novice_Leather = {
		Name = "Novice Leather Pants",
		Slot = "LowerBody",
		ArmorType = "Leather",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { PhysicalDefense = 2, MovementSpeed = 0.01 },
	},
	Cloak_Novice_Leather = {
		Name = "Explorer's Cloak",
		Slot = "Cloak",
		ArmorType = "Leather",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { MovementSpeed = 0.05, Evasion = 0.01 },
	},

	-- ==========================================
	-- PLATE ARMOR (Swordsman, Knights, Battle Mages)
	-- ==========================================
	Headwear_Novice_Plate = {
		Name = "Basic Iron Helm",
		Slot = "Headwear",
		ArmorType = "Plate",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { PhysicalDefense = 3, Vitality = 1 },
	},
	Shoulder_Novice_Plate = {
		Name = "Novice Iron Pauldrons",
		Slot = "Shoulder",
		ArmorType = "Plate",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { PhysicalDefense = 2, Vitality = 1 },
	},
	UpperBody_Novice_Plate = {
		Name = "Novice Iron Chestplate",
		Slot = "UpperBody",
		ArmorType = "Plate",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { PhysicalDefense = 5, Vitality = 2, Tenacity = 0.01 },
	},
	Waist_Novice_Plate = {
		Name = "Novice Iron Sash",
		Slot = "Waist",
		ArmorType = "Plate",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { PhysicalDefense = 1, Vitality = 1 },
	},
	LowerBody_Novice_Plate = {
		Name = "Novice Iron Greaves",
		Slot = "LowerBody",
		ArmorType = "Plate",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { PhysicalDefense = 3, MovementSpeed = -0.01 },
	},
	Cloak_Novice_Plate = {
		Name = "Steel Cloak",
		Slot = "Cloak",
		ArmorType = "Plate",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { PhysicalDefense = 2 },
	},

	-- ==========================================
	-- UNIVERSAL ACCESSORIES
	-- ==========================================
	Ring_Iron = {
		Name = "Simple Iron Ring",
		Slot = "Ring",
		ArmorType = "Universal",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { Strength = 1, PhysArmorPen = 1 },
	},
	Necklace_Copper = {
		Name = "Copper Necklace",
		Slot = "Necklace",
		ArmorType = "Universal",
		Tier = 1,
		Rarity = "White",
		LevelReq = 1,
		Stats = { Intelligence = 1, MagicArmorPen = 1 },
	},
}
